export interface Capsule {
  id: string;
  category: string;
  style: string;
  composition: string;
  colorScheme: string;
  platform: string;
  stage: string;
  why: string;
  hooks: string[];
  demoImage: string;
  aspectRatio: string;
}

export const CATEGORIES = [
  { id: 'tech', emoji: '🎧', name: '数码3C' },
  { id: 'beauty', emoji: '🧴', name: '美妆护肤' },
  { id: 'food', emoji: '☕', name: '食品饮料' },
  { id: 'fashion', emoji: '👟', name: '服饰鞋包' },
  { id: 'home', emoji: '🏠', name: '家居生活' },
  { id: 'fitness', emoji: '💪', name: '运动健康' },
];

export const CAPSULES: Capsule[] = [
  // ===== 数码3C =====
  {
    id: 'tech-01',
    category: 'tech',
    style: '极简白底 · 产品即主角',
    composition: '中心对称构图，80%留白，产品占比20%',
    colorScheme: '纯白背景 + 品牌单色强调',
    platform: 'FB / IG Feed',
    stage: '冷启动',
    why: '白底图在FB算法中CTR高于场景图18%，新客认知成本最低',
    hooks: ['This is not a headphone', '98% noise. Gone.', 'Hear the difference'],
    demoImage: '/demo/tech_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'tech-02',
    category: 'tech',
    style: 'UGC原生感 · 真实开箱',
    composition: '45°俯拍，桌面自然散落，带手入镜',
    colorScheme: '暖色调，自然光感',
    platform: 'IG Story / TikTok',
    stage: '放量',
    why: '原生感素材在IG Story的滑动率比精修图高34%，用户以为是朋友分享',
    hooks: ['终于找到这款', '用了3个月才分享', '真实开箱不滤镜'],
    demoImage: '/demo/tech_02.webp',
    aspectRatio: '9:16',
  },
  {
    id: 'tech-03',
    category: 'tech',
    style: '对比冲击 ·  before/after',
    composition: '左右对半分屏，强烈对比',
    colorScheme: '左暗右亮，或左杂右净',
    platform: 'FB Ad',
    stage: '抢注意',
    why: '对比图在信息流中的停留时间比普通图长2.3秒，足够传递核心卖点',
    hooks: ['Before vs After', 'With vs Without', 'Old way vs New way'],
    demoImage: '/demo/tech_03.webp',
    aspectRatio: '16:9',
  },
  {
    id: 'tech-04',
    category: 'tech',
    style: '生活方式 · 场景植入',
    composition: '环境占比70%，产品自然融入',
    colorScheme: '场景真实色调，产品微提亮',
    platform: 'IG Feed / Pinterest',
    stage: '品牌认知',
    why: '场景图让用户想象"我也能这样"，收藏率比白底图高47%',
    hooks: ['My everyday essential', 'Weekend vibes', 'Set the mood'],
    demoImage: '/demo/tech_06.webp',
    aspectRatio: '4:5',
  },
  {
    id: 'tech-05',
    category: 'tech',
    style: '痛点场景 · 问题放大',
    composition: '特写问题瞬间，表情/动作夸张',
    colorScheme: '偏冷偏暗，突出不适感',
    platform: 'FB / TikTok',
    stage: '转化',
    why: '痛点前置的素材转化率比卖点前置高22%，因为用户先认同问题',
    hooks: ['Tired of this?', 'Still doing it the old way?', 'This changes everything'],
    demoImage: '/demo/tech_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'tech-06',
    category: 'tech',
    style: '社交证明 · 数据说话',
    composition: '产品+大数字+短文案，海报感',
    colorScheme: '深色底+高对比亮色数字',
    platform: 'FB Ad / IG Feed',
    stage: '信任',
    why: '带具体数字的素材信任度提升41%，"10万+用户"比"畅销"有效',
    hooks: ['100,000+ sold', 'Rated 4.9/5', '#1 Bestseller'],
    demoImage: '/demo/tech_03.webp',
    aspectRatio: '1:1',
  },

  // ===== 美妆护肤 =====
  {
    id: 'beauty-01',
    category: 'beauty',
    style: '极简白底 · 产品即主角',
    composition: '中心对称，花瓣/水滴点缀',
    colorScheme: '纯白+品牌粉/金',
    platform: 'IG Feed / FB',
    stage: '冷启动',
    why: '美妆白底图在IG的保存率最高，用户喜欢"干净"的视觉',
    hooks: ['One drop. All day glow.', 'Your skin but better', 'Clean beauty'],
    demoImage: '/demo/beauty_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'beauty-02',
    category: 'beauty',
    style: 'UGC原生感 · 真实测评',
    composition: '自拍角度，浴室/化妆台背景',
    colorScheme: '自然肤色，暖光',
    platform: 'IG Story / TikTok',
    stage: '放量',
    why: '真人出镜的素材在TikTok完播率比产品图高56%',
    hooks: ['Honest review', '3 weeks in', 'Not sponsored, just obsessed'],
    demoImage: '/demo/beauty_03.webp',
    aspectRatio: '9:16',
  },
  {
    id: 'beauty-03',
    category: 'beauty',
    style: '对比冲击 · before/after',
    composition: '左右脸对比，同光线同角度',
    colorScheme: '自然肤色对比，无滤镜',
    platform: 'FB Ad',
    stage: '抢注意',
    why: 'before/after是美妆永远的CTR王者，停留时间最长',
    hooks: ['Week 1 vs Week 4', 'The glow up is real', 'See the difference'],
    demoImage: '/demo/beauty_02.webp',
    aspectRatio: '16:9',
  },
  {
    id: 'beauty-04',
    category: 'beauty',
    style: '生活方式 · 晨间仪式',
    composition: '俯拍桌面，产品+咖啡+阳光',
    colorScheme: '暖金色调，晨光感',
    platform: 'IG Feed / Pinterest',
    stage: '品牌认知',
    why: '"生活方式"类素材让品牌溢价提升30%，用户买的不是产品是生活',
    hooks: ['Morning ritual', 'Self-care Sunday', 'Glow from within'],
    demoImage: '/demo/beauty_04.webp',
    aspectRatio: '4:5',
  },
  {
    id: 'beauty-05',
    category: 'beauty',
    style: '痛点场景 · 问题肌特写',
    composition: '问题部位特写，引发共鸣',
    colorScheme: '偏冷，突出不适感',
    platform: 'FB / TikTok',
    stage: '转化',
    why: '展示问题再展示解决方案的素材，转化率比直接展示高35%',
    hooks: ['Struggling with this?', 'Finally found it', 'No more hiding'],
    demoImage: '/demo/beauty_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'beauty-06',
    category: 'beauty',
    style: '社交证明 · 明星同款',
    composition: '产品+名人/网红剪影暗示',
    colorScheme: '黑金奢华感',
    platform: 'FB Ad / IG',
    stage: '信任',
    why: '"As seen on"类素材点击率比普通高28%，借势效应明显',
    hooks: ['Celebrity secret', 'Viral on TikTok', 'Sold out 3x'],
    demoImage: '/demo/beauty_02.webp',
    aspectRatio: '1:1',
  },

  // ===== 食品饮料 =====
  {
    id: 'food-01',
    category: 'food',
    style: '极简白底 · 产品即主角',
    composition: '俯拍，产品居中，少量配料点缀',
    colorScheme: '纯白+食物本色',
    platform: 'IG Feed / FB',
    stage: '冷启动',
    why: '食物白底图在IG的点赞率比场景图高15%，"干净"是关键',
    hooks: ['Pure. Simple. Perfect.', 'Just 3 ingredients', 'No additives'],
    demoImage: '/demo/coffee_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'food-02',
    category: 'food',
    style: 'UGC原生感 · 真实享用',
    composition: '手持角度，第一人称视角',
    colorScheme: '自然光，暖色调',
    platform: 'IG Story / TikTok',
    stage: '放量',
    why: '第一人称视角的素材在TikTok分享率最高，用户觉得"我也想吃"',
    hooks: ['POV: your morning', 'First sip feeling', 'This sound'],
    demoImage: '/demo/coffee_03.webp',
    aspectRatio: '9:16',
  },
  {
    id: 'food-03',
    category: 'food',
    style: '对比冲击 · 原料vs成品',
    composition: '左右分屏，原料→成品过程',
    colorScheme: '原料偏暗，成品鲜亮',
    platform: 'FB Ad',
    stage: '抢注意',
    why: '展示"从原料到成品"的过程图，信任度提升38%',
    hooks: ['From farm to cup', 'Bean to brew', 'Real ingredients'],
    demoImage: '/demo/coffee_02.webp',
    aspectRatio: '16:9',
  },
  {
    id: 'food-04',
    category: 'food',
    style: '生活方式 · 场景氛围',
    composition: '环境为主，产品自然融入桌面',
    colorScheme: '暖色调，午后阳光感',
    platform: 'IG Feed / Pinterest',
    stage: '品牌认知',
    why: '"场景氛围"类素材让用户产生"我也想过这种生活"的向往',
    hooks: ['Slow living', 'Afternoon ritual', 'Weekend treat'],
    demoImage: '/demo/coffee_04.webp',
    aspectRatio: '4:5',
  },
  {
    id: 'food-05',
    category: 'food',
    style: '痛点场景 · 替代诱惑',
    composition: '左边不健康选择，右边你的产品',
    colorScheme: '左暗右亮，对比强烈',
    platform: 'FB / TikTok',
    stage: '转化',
    why: '"替代"类素材（用我代替坏习惯）转化率比直接推销高40%',
    hooks: ['Swap this for that', 'Guilty pleasure, upgraded', 'Same taste, better for you'],
    demoImage: '/demo/coffee_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'food-06',
    category: 'food',
    style: '社交证明 · 销量/好评',
    composition: '产品+大数字+五星+用户头像',
    colorScheme: '暖色底+金色强调',
    platform: 'FB Ad',
    stage: '信任',
    why: '食品类带"X万人选择"的素材，新客转化率提升33%',
    hooks: ['1M+ cups sold', '4.9★ from 12K reviews', 'Sold out in 24h'],
    demoImage: '/demo/coffee_02.webp',
    aspectRatio: '1:1',
  },

  // ===== 服饰鞋包 =====
  {
    id: 'fashion-01',
    category: 'fashion',
    style: '极简白底 · 产品即主角',
    composition: '单品平铺或挂拍，无干扰',
    colorScheme: '纯白+产品本色',
    platform: 'IG Feed / FB',
    stage: '冷启动',
    why: '服饰白底图在IG的点击率高，用户想看清楚细节',
    hooks: ['The perfect fit', 'Details matter', 'Built different'],
    demoImage: '/demo/sport_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'fashion-02',
    category: 'fashion',
    style: 'UGC原生感 · 真实穿搭',
    composition: '全身镜自拍，日常背景',
    colorScheme: '自然光，真实色调',
    platform: 'IG Story / TikTok',
    stage: '放量',
    why: '真实穿搭视频在TikTok的完播率比专业拍摄高62%',
    hooks: ['OOTD', 'How I style it', 'Real review'],
    demoImage: '/demo/sport_03.webp',
    aspectRatio: '9:16',
  },
  {
    id: 'fashion-03',
    category: 'fashion',
    style: '对比冲击 · 穿搭前后',
    composition: '同一个人，穿搭前vs穿搭后',
    colorScheme: '左普通右亮眼',
    platform: 'FB Ad / TikTok',
    stage: '抢注意',
    why: '"改造"类素材在服饰品类CTR最高，因为每个人都想变得更好',
    hooks: ['Transformation', 'Before & After', 'Level up'],
    demoImage: '/demo/sport_02.webp',
    aspectRatio: '16:9',
  },
  {
    id: 'fashion-04',
    category: 'fashion',
    style: '生活方式 · 场景穿搭',
    composition: '街头/咖啡/办公室场景，自然走动',
    colorScheme: '场景色调，产品突出',
    platform: 'IG Feed / Pinterest',
    stage: '品牌认知',
    why: '场景穿搭让用户想象"我穿这个会是什么样"，收藏率最高',
    hooks: ['City walk ready', 'Coffee run chic', 'Office to evening'],
    demoImage: '/demo/sport_04.webp',
    aspectRatio: '4:5',
  },
  {
    id: 'fashion-05',
    category: 'fashion',
    style: '痛点场景 ·  uncomfortable vs comfortable',
    composition: '左边难受表情+旧鞋，右边舒服+新鞋',
    colorScheme: '左灰右亮',
    platform: 'FB / TikTok',
    stage: '转化',
    why: '"解决痛点"类素材在鞋类转化率最高，因为舒适是刚需',
    hooks: ['Finally comfortable', 'No more blisters', 'Walk all day'],
    demoImage: '/demo/sport_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'fashion-06',
    category: 'fashion',
    style: '社交证明 · 名人/限量',
    composition: '产品+限量标识/名人暗示',
    colorScheme: '黑金/限量红',
    platform: 'FB Ad / IG',
    stage: '信任',
    why: '限量/联名类素材在服饰品类制造稀缺感，转化率提升45%',
    hooks: ['Limited drop', 'Collab of the year', 'Only 500 made'],
    demoImage: '/demo/sport_02.webp',
    aspectRatio: '1:1',
  },

  // ===== 家居生活 =====
  {
    id: 'home-01',
    category: 'home',
    style: '极简白底 · 产品即主角',
    composition: '产品居中，极简背景',
    colorScheme: '纯白+产品木色/金属色',
    platform: 'IG Feed / FB',
    stage: '冷启动',
    why: '家居白底图让产品细节清晰可见，适合新客第一次认知',
    hooks: ['Less is more', 'Designed for living', 'Form meets function'],
    demoImage: '/demo/robot_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'home-02',
    category: 'home',
    style: 'UGC原生感 · 真实使用',
    composition: '生活场景，产品自然使用中',
    colorScheme: '自然家居光，暖色调',
    platform: 'IG Story / TikTok',
    stage: '放量',
    why: '"真实家"场景在TikTok的分享率最高，用户觉得可信',
    hooks: ['Real home, real use', 'Not staged', 'How we actually use it'],
    demoImage: '/demo/robot_02.webp',
    aspectRatio: '9:16',
  },
  {
    id: 'home-03',
    category: 'home',
    style: '对比冲击 ·  before/after',
    composition: '同角度，改造前vs改造后',
    colorScheme: '左乱右整，对比强烈',
    platform: 'FB Ad / Pinterest',
    stage: '抢注意',
    why: '家居改造前后对比是Pinterest上保存率最高的内容类型',
    hooks: ['Before & After', 'The transformation', 'Same space, new feel'],
    demoImage: '/demo/robot_03.webp',
    aspectRatio: '16:9',
  },
  {
    id: 'home-04',
    category: 'home',
    style: '生活方式 · 理想家',
    composition: '全景或广角，展示理想生活状态',
    colorScheme: '温暖明亮，阳光感',
    platform: 'IG Feed / Pinterest',
    stage: '品牌认知',
    why: '"理想家"场景让用户产生向往，品牌溢价空间最大',
    hooks: ['Dream home', 'Sunday morning', 'Cozy vibes'],
    demoImage: '/demo/robot_04.webp',
    aspectRatio: '4:5',
  },
  {
    id: 'home-05',
    category: 'home',
    style: '痛点场景 · 混乱vs有序',
    composition: '左边混乱场景，右边产品解决后',
    colorScheme: '左暗乱右亮整',
    platform: 'FB / TikTok',
    stage: '转化',
    why: '"解决问题"类素材在家居品类转化率最高，因为购买动机明确',
    hooks: ['Finally organized', 'No more clutter', 'Small space, big solution'],
    demoImage: '/demo/robot_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'home-06',
    category: 'home',
    style: '社交证明 · 销量/口碑',
    composition: '产品+大数字+用户真实评价截图',
    colorScheme: '暖白底+绿色/金色评分',
    platform: 'FB Ad',
    stage: '信任',
    why: '家居类带真实评价的素材，新客信任度提升36%',
    hooks: ['50K+ happy homes', 'Rated 4.8★', 'Best seller 2026'],
    demoImage: '/demo/robot_03.webp',
    aspectRatio: '1:1',
  },

  // ===== 运动健康 =====
  {
    id: 'fitness-01',
    category: 'fitness',
    style: '极简白底 · 产品即主角',
    composition: '产品居中，运动元素点缀',
    colorScheme: '纯白+品牌活力色',
    platform: 'IG Feed / FB',
    stage: '冷启动',
    why: '运动产品白底图在IG的专业感最强，适合建立品牌认知',
    hooks: ['Engineered for performance', 'Lightest yet', 'Built to move'],
    demoImage: '/demo/ring_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'fitness-02',
    category: 'fitness',
    style: 'UGC原生感 · 真实训练',
    composition: '运动中的真实抓拍，汗水/努力感',
    colorScheme: '自然运动光线，偏暖',
    platform: 'IG Story / TikTok',
    stage: '放量',
    why: '真实训练场景在TikTok的完播率比精修图高71%，因为真实才有共鸣',
    hooks: ['Real workout', 'No filter, just sweat', 'Training day'],
    demoImage: '/demo/ring_02.webp',
    aspectRatio: '9:16',
  },
  {
    id: 'fitness-03',
    category: 'fitness',
    style: '对比冲击 · 数据可视化',
    composition: '产品+数据图表+身体变化',
    colorScheme: '深色底+荧光数据色',
    platform: 'FB Ad',
    stage: '抢注意',
    why: '"数据说话"在健康品类最可信，用户相信数字不相信形容词',
    hooks: ['30 days later', 'The numbers speak', 'Track every beat'],
    demoImage: '/demo/ring_03.webp',
    aspectRatio: '16:9',
  },
  {
    id: 'fitness-04',
    category: 'fitness',
    style: '生活方式 · 健康日常',
    composition: '晨跑/瑜伽/健康餐场景，产品自然出现',
    colorScheme: '清晨光线，清新色调',
    platform: 'IG Feed / Pinterest',
    stage: '品牌认知',
    why: '"健康生活"场景让用户产生"我也想这样生活"的认同',
    hooks: ['Morning routine', 'Healthy habits', 'Balance'],
    demoImage: '/demo/ring_04.webp',
    aspectRatio: '4:5',
  },
  {
    id: 'fitness-05',
    category: 'fitness',
    style: '痛点场景 · 旧方式vs新方式',
    composition: '左边笨重旧设备，右边你的轻便产品',
    colorScheme: '左灰重右亮轻',
    platform: 'FB / TikTok',
    stage: '转化',
    why: '"替代升级"类素材在运动品类转化率最高，因为用户已有认知',
    hooks: ['Upgrade your run', 'Lighter than your phone', 'Finally free'],
    demoImage: '/demo/ring_01.webp',
    aspectRatio: '1:1',
  },
  {
    id: 'fitness-06',
    category: 'fitness',
    style: '社交证明 · 运动员/社区',
    composition: '产品+运动员剪影/社区活动',
    colorScheme: '运动品牌经典配色',
    platform: 'FB Ad / IG',
    stage: '信任',
    why: '"专业运动员选择"在运动品类信任度最高，借势效应最强',
    hooks: ['Trusted by pros', 'Join 100K runners', 'Community powered'],
    demoImage: '/demo/ring_03.webp',
    aspectRatio: '1:1',
  },
];

export function getRandomCapsule(categoryId: string): Capsule {
  const pool = CAPSULES.filter(c => c.category === categoryId);
  return pool[Math.floor(Math.random() * pool.length)];
}
